### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Anzo52** [Anzo52/mal-u-check#1]
Need help translating into European languages!

**Comment by kruczyna** [comment]
hi @Anzo52! What languages you need specifically?

**Comment by Anzo52** [comment]
Hey @kruczyna! Anything Eastern, specifically I'm hoping Russian speakers will find this useful.

**Comment by kruczyna** [comment]
@Anzo52 I see, unfortuanetlly can provide Polish only, whould that be something useful for you? I am wondering what file exactly is there that needs translation? 🤔

**Comment by Anzo52** [comment]
Killing the project
